### ISSUE TITLE
Create reusable ESLint configuration

### ISSUE THREAD

**Issue by harjot1singh** [shabados/eslint-config#1]
## Summary

We'd like to reuse our ESLint configuration across the organization, so that it's easier to spin up new repositories consistently.

It should be possible to combine default, React, and TypeScript variants together, depending on the project.

## Approach

- Move reusable config to this repo from shabados/mobile
- Create different entrypoints
- Publish as npm package

**Comment by Harjot1Singh** [comment]
Done in 57e2298f3a59ae9217663ca071a8d88529f49308

**Comment by harjot1singh** [comment]
Done in shabados/mobile@57e2298f3a59ae9217663ca071a8d88529f49308
